# import = ["~/.config/alacritty/themes/nord.toml"]
# import = ["~/.config/alacritty/themes/gruvbox-dark.toml"]
import = ["~/.config/alacritty/themes/kanagawa_wave.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Transparent"
padding = { x = 10, y = 25 }

[font]
normal = { family = "0xProto Nerd Font Mono", style = "Regular" }
size = 22
