import = ["~/.config/alacritty/themes/nord.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Transparent"
padding = { x = 10 }

[font]
normal = { family = "0xProto Nerd Font Mono", style = "Regular" }
size = 22
