"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = '$directory$character'

[character]
success_symbol = '[>](bold purple)'
error_symbol = '[?](bold yellow)'
vimcmd_symbol = '[|](bold purple)'
vimcmd_replace_symbol = '[|](bold red)'

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
