theme = "gruvbox_transparent" # "dark_plus" catppuccin_frappe
# "diagnostic.error" = { underline = { style = "curl", color = "red" } }

[editor]
line-number = "absolute"
mouse = true
color-modes = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
# J = "half_page_down"
# K = "half_page_up"
ret = ["move_line_down", "goto_first_nonwhitespace"] # Maps the enter key to move to start of next line
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
# "space" = { ">" = ["normal_mode"] }
# "space" = { "``" = ["search_mode"] }

# [commands.write]
# shell = "pwd"
