[[language]]
name = "tsx"
scope = "scope.ts"
roots = ["tsconfig.ts"]
file-types = ["tsx"]
language-servers = ["typescript-language-server", "tailwindcss-react", "vscode-eslint-language-server"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[language-server.tailwindcss-react]
language-id = "typescriptreact"
command = "tailwindcss-language-server"
args = ["--stdio"]
config = {}

[[language]]
name = "python"
language-servers = [ "pyright" ]

# use-grammars = { only = [ "rust", "ruby", "javascript", "jsx", "typescript-language-server", "kotlin", "ruby", "python", "typescript-deno", "svelte"] }

# [language-server.javscript]
# command = "typescript-language-server"
# args = ["--stdio"]
# [language-server.javscriptreact]
# command = "typescript-language-server"
# args = ["--stdio"]

# [[language]]
# name = "javascript"
# scope = "source.js"
# roots = ["package.json"]
# file-types = ["js", "ts"]
# indent = { tab-width = 2, unit = " " }
# language-id = "javascript"

# [[language]]
# name = "javascriptreact"
# scope = "source.jsx"
# roots = ["package.json"]
# file-types = ["jsx", "tsx"]
# indent = { tab-width = 2, unit = " " }
# language-id = "javascriptreact"

# [[language]]
# name = "tailwindcss"
# scope = "source.css"
# injection-regex = "(postcss|css|html|jsx|tsx)"
# file-types = ["css", "jsx", "tsx"]
# roots = ["tailwind.config.js","tailwind.config.cjs"]
# language-servers = ["tailwindcss-language-server"]
# language-servers = { command = "tailwindcss-language-server", args = ["-vvv", "--stdio"] }
